env:
  global:
  - DEBUG='* -mocha:* -superagent -express:* -base:validator -base:entity'
language: node_js
node_js:
- '0.10'
script: npm test
deploy:
  provider: heroku
  api_key:
    secure: CcESSZZF+qsck+AH5GWZnSBIJu+xIn2u43ykfiVkyAFQmAhEUib04JFuN8XJ0CWLCoAQSZoq+Gf5yxUwxqwTscg6sT+OOBEagVbD7r7TXbjXDKSigCo4vZBI+wrMh2Av8GQAeuV1VsvHPTnXH0FLqm+iIPsE2kLJpUnFYM5KSe8=
  app: taskcluster-events
  on:
    repo: taskcluster/taskcluster-events
before_install:
- openssl aes-256-cbc -K $encrypted_da51d083b616_key -iv $encrypted_da51d083b616_iv
  -in task-graph-scheduler.conf.json.enc -out task-graph-scheduler.conf.json -d
