env:
  global:
  - DEBUG='* -mocha:* -superagent -express:* -base:validator -base:entity'
language: node_js
node_js:
- '4'
script: npm test
#before_install:
#- openssl aes-256-cbc -K $encrypted_fe3b06c071a6_key -iv $encrypted_fe3b06c071a6_iv
#  -in taskcluster-events.conf.json.enc -out taskcluster-events.conf.json -d

# encrpyt channel name to get around issue
# https://github.com/travis-ci/travis-ci/issues/1094
notifications:
  irc:
    channels:
      # encrpyted string was "irc.mozilla.org#taskcluster-bots"
      - secure: "GCcDt7IVSe8jPC0QfUgCVpkESeZZ/ThAA7+BoF30rHGDWXbOzu4dMXjT8D7/cC+y6nhh6mgueYPtxg+mdWVBMwUwncMSc+4BiMBQykF596b/yxqM/UlKs5y1in+7xhQ6+hNZL/EzICcq10XXQT9bTuRf2Oa/jdpQwddzwnCSoqQ="
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
