env:
  global:
  - DEBUG='* -mocha:* -superagent -express:* -base:validator -base:entity'
language: node_js
node_js:
- '0.10'
script: npm test
deploy:
  provider: heroku
  strategy: git
  app: taskcluster-events
  username:
    secure: CiPfQgE2eBkNjYOiK/frZTm50HRD3Zh7VAvjMF+pwiKpuTLfHATLT/yxyS9Jq1+jtD/sdxvN5kv99+oHCSlgfyljRESq3BWbPoVBlWPKecfXlXMgKw6KimQ60VjpxyhbYDXKKu/aEpfnGCMzNyGpyiYmFQEybwDmG10f3ipNoRg=
  password:
    secure: fdMWxe3OVfgLzZ33km0dEKRxO5hykhgJW7/aDHy46JmyBL2gPTjzs6RKfq7WG8XUK941n0NxREvbE4tiIXWdBIitTs5AHqmxwhEqmed6dw9fM//xL4XRQeGfOthg7ClDkAMW1N1C2XW9wWgAbM/1j7ZjRmEfi8+8YcYtXXDcfqQ=
  on:
    repo: taskcluster/taskcluster-events
before_install:
- openssl aes-256-cbc -K $encrypted_fe3b06c071a6_key -iv $encrypted_fe3b06c071a6_iv
  -in taskcluster-events.conf.json.enc -out taskcluster-events.conf.json -d
