defaults:
  hostname:           https://events.taskcluster.net
  port:               !env:number PORT
  port:               undefined
  forceSSL:           false
  trustProxy:         false
  influx:
    maxDelay:         5*60
    maxPendingPoints: 250
  events:
    statsComponent:   events

test: # profile 'test'
  hostname:           http://localhost
  port:               12345
  forceSSL:           false
  pulse:
    username:         !env PULSE_USERNAME
    password:         !env PULSE_PASSWORD
  taskcluster:
    credentials:
      accessToken:    !env TASKCLUSTER_ACCESS_TOKEN
      clientId:       !env TASKCLUSTER_CLIENT_ID
# Add more profiles here
